name: Update emacs-overlay

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Rebase on top of nix-community/emacs-overlay/master
        run: |
          git remote add upstream "https://github.com/nix-community/emacs-overlay"
          git checkout master
          git pull upstream master
          git push origin master
          git checkout "${{ github.ref_name }}"
          git rebase master
          git push --force origin "${{ github.ref_name }}"
